random_seed: 0
work_dir: /data/ahmed026/MM_SLT/test

batch_size: 4
test_batch_size: 2

num_worker: 0
device: cuda:0

feeder: dataset.loader_img.BaseFeeder
feeder_ft: dataset.loader_ft.PrecomputedFeatureDataset
include_sp: False
include_pose: False
p2hm: False
sign_hidden_size: 1024
sp_hidden_size: 2048
pose_hidden_size: 1024

phase: train
dataset: phoenix2014-T
num_epoch: 1000
num_warmpup_epochs: 50
validation_interval: 5
patience: 5
monitor_bleu: True
score_dependent_scheduler: True

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  learning_ratio: 1
  gamma: 0.2
  weight_decay: 0.0001
  start_epoch: 0

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0
  frame_interval: 1
  image_scale: 1.0
  input_size: 224

slr: modules.slr.SLRModel
slr_weights: /Users/gufran/Developer/Projects/AI/MLLM_SLT/ckpt/swinB_SLR.pt

model: modules.flant5.FlanT5
llm: google/flan-t5-xl

slr_args:
  c2d_type: swinb_mstcn-3
  conv_type: 2
  use_bn: 1
  share_classifier: 1
  weight_norm: True

llm_args:
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  max_txt_len: 64
  tuning_mode: lora
  prompt: "Translate the given sentence into"