dataset_root: /Users/gufran/Developer/data/phoenix2014T
dict_path: ./preprocess/phoenix2014-T/gloss_dict.npy
feature_dir: /home/ahmedubc/projects/aip-lsigal/ahmedubc/datasets/phoenix2014T/fullFrame-256x256px

# sp_path: /home/ahmedubc/projects/aip-lsigal/ahmedubc/datasets/spamo/sp/clip-vit-large-patch14_feat_Phoenix14T
# sp_path: /home/ahmedubc/projects/aip-lsigal/ahmedubc/datasets/dino_sp/sp/dinov2-giant-imagenet1k-1-layer_feat_phoenix2014-T
sp_path: /home/ahmedubc/projects/aip-lsigal/ahmedubc/datasets/features

mo_path: /home/ahmedubc/projects/aip-lsigal/ahmedubc/datasets/spamo/mo/mae_feat_Phoenix14T
phm_path: /home/ahmedubc/projects/aip-lsigal/ahmedubc/datasets/spamo/posp/clip-vit-large-patch14_feat_Phoenix14T
pose_path: /home/ahmedubc/projects/aip-lsigal/ahmedubc/datasets/pose

pose_encoder_config_path: /home/ahmedubc/projects/aip-lsigal/ahmedubc/MM_SLT/configs/phoenix-2014t_s2g.yaml

language: German